version: "3.5"

services:
  replica01: &api
    container_name: replica01
    hostname: replica01
    ports:
      - '3001:3000'
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.15"
          memory: "250MB"
    depends_on:
      - postgres
  replica02:
    <<: *api
    container_name: replica02
    hostname: replica02
    ports:
      - '3002:3000'
  nginx:
    image: nginx:latest
    volumes:
      - ./config/loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - replica01
      - replica02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
  # envoy:
  #   image: envoyproxy/envoy:v1.29-latest
  #   container_name: envoy
  #   volumes:
  #      - ./config/loadbalancer/:/etc/envoy/
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"
  #         memory: "50MB"
  #   command: [ "envoy", "-c", "/etc/envoy/envoy.yaml" ]
  #   depends_on:
  #     - replica01
  #     - replica02
  
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "240MB"
networks:
  default:
    driver: bridge
    name: rinha-2024-q1